name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
          # Create directory if it doesn't exist
          mkdir -p /home/ec2-user/deploy-nodejs-express-api-to-ec2-container

          # Navigate to the project directory
          cd /home/ec2-user/deploy-nodejs-express-api-to-ec2-container

          # Pull the latest code
          git pull origin main || git clone https://github.com/dasingh9/deploy-nodejs-express-api-to-ec2-container.git .

          # Build and run the Docker container
          sudo docker build -t nodejs-express-api .
          sudo docker stop nodejs-express-container || true
          sudo docker rm nodejs-express-container || true
          sudo docker run -d -p 80:3000 --name nodejs-express-container nodejs-express-api
        EOF